### ISSUE TITLE
impossibile to run Server8889.py

### ISSUE THREAD

**Issue by leonealex** [cicciovo/homebridge-samsung-airconditioner#19]
When i try to run Server8889.py both Mac&linux, I read this message.

`Listening on localhost:8889
Traceback (most recent call last):
  File "Server8889.py", line 53, in <module>
    main()
  File "Server8889.py", line 47, in main
    server.socket = ssl.wrap_socket(server.socket, certfile = '/usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m', server_side=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory
Alessandro@MBP15 homebridge-samsung-airconditioner % 
`

and I don't know why!
i also try to install manually the certificate both Mac & linux, try to modify Server8889 with my path but nothing change.
can someone tell me what appen?

**Comment by cicciovo** [comment]
Dice che non ti trova il certificato... eventualmente cambia patch e fai un percorso a te noto...

F.B.

Il giorno 3 mar 2020, alle ore 15:30, leonealex <notifications@github.com> ha scritto:

﻿

When i try to run Server8889.py both Mac&linux, I read this message.

Listening on localhost:8889 Traceback (most recent call last): File "Server8889.py", line 53, in <module> main() File "Server8889.py", line 47, in main server.socket = ssl.wrap_socket(server.socket, certfile = '/usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m', server_side=True) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 931, in wrap_socket ciphers=ciphers) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 542, in __init__ self._context.load_cert_chain(certfile, keyfile) IOError: [Errno 2] No such file or directory Alessandro@MBP15 homebridge-samsung-airconditioner %

and I don't know why!
i also try to install manually the certificate both Mac & linux, try to modify Server8889 with my path but nothing change.
can someone tell me what appen?

**Comment by EliBuechler** [comment]
i think I can see a problem with the file but I may be wrong, the homebridge directory being referenced is incorrect, from what I see it should be homebridge-samsung-smart-aircon

there was a reference to the name changing and that files would be updated from homebridge-samsung-aircon-8888 that just does not exit but is referenced incorrectly throughout the documentation. I use Hoobs and have had no luck as I am no programmer, but have uninstall for now until there is an update to documentation. How did anyone manage to make this work>?
