### ISSUE TITLE
SSL: CA_MD_TOO_WEAK

### ISSUE THREAD

**Issue by Leon99** [cicciovo/homebridge-samsung-airconditioner#22]
```
python2 Server8889.py
Listening on localhost:8889
Traceback (most recent call last):
  File "Server8889.py", line 53, in <module>
    main()
  File "Server8889.py", line 47, in main
    server.socket = ssl.wrap_socket(server.socket, certfile='/usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem', server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2815)
```
This is in Ubuntu.
Any ideas much appreciated.

**Comment by Leon99** [comment]
Duplicate of https://github.com/cicciovo/homebridge-samsung-airconditioner/issues/17
