### ISSUE TITLE
cannot run Server8889.py

### ISSUE THREAD

**Issue by gcherem** [cicciovo/homebridge-samsung-airconditioner#23]
I get the followinr error:

```
Listening on localhost:8889
Traceback (most recent call last):
  File "Server8889.py", line 53, in <module>
    main()
  File "Server8889.py", line 47, in main
    server.socket = ssl.wrap_socket(server.socket, certfile='/Users/francescobosco/Desktop/ac14k_m.pem', server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory
```

Seems the directory /Users/francescobosco/Desktop/ is hardcoded and there is one ac14k_m.pem in the same folder as 
Server8889.py. Then I changed the source to get it but now I get:

```
Listening on localhost:8889
Traceback (most recent call last):
  File "Server8889.py", line 53, in <module>
    main()
  File "Server8889.py", line 47, in main
    server.socket = ssl.wrap_socket(server.socket, certfile='ac14k_m.pem', server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 931, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 542, in __init__
    self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2815)
```

Any idea?

**Comment by gcherem** [comment]
Please close this issue.

Found solution on [#17 ](url)

**Comment by gcherem** [comment]
Found solution on #17
