### ISSUE TITLE
Synology NAS

### ISSUE THREAD

**Issue by HajLender** [cicciovo/homebridge-samsung-airconditioner#4]
Hello,

I am trying to migrate my homebridge server to synology NAS. 
I am using oznu/homebridge.

I don't know where to put or how to install the certificate on the synology NAS. On mac it was easy, I just double clicked it, but of course it does not work on the synology NAS.

Can anybody help me please?

More details:
During the installation I get this errors, but at the end it shows succesful installation
![aaaa](https://user-images.githubusercontent.com/29841504/38781082-862c3a62-40e0-11e8-94e3-798517cd9658.png)
![aaa](https://user-images.githubusercontent.com/29841504/38781083-86569cbc-40e0-11e8-87ba-71ef770b271c.png)

I am using this in config.json

        {
            "accessory": "SamsungAirconditioner",
            "name": "Climatizzatore",
            "ip": "192.168.1.152",
            "token": "FF94H43Wn4",
            "patchCert": "/homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem"
        },
        {
            "accessory": "SamsungAirconditioner",
            "name": "Climatizzatore2",
            "ip": "192.168.1.149",
            "token": "1XbH4i120U",
            "patchCert": "/homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem"
        }

When I am running homebridge and click on the AC in homekit application I get this error:

[2018-4-15 19:08:35] [Climatizzatore] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer F9H4H43Wn4" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.152:8888/devices|jq '.Devices[0].Operation.power'
[2018-4-15 19:08:35] [Climatizzatore] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer F9H4H43Wn4" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.152:8888/devices|jq '.Devices[0].Mode.modes[0]'
[2018-4-15 19:08:35] [Climatizzatore] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer F9H4H43Wn4" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.152:8888/devices|jq '.Devices[0].Temperatures[0].desired'
[2018-4-15 19:08:35] [Climatizzatore] Mettere modalita
[2018-4-15 19:08:35] [Climatizzatore] curl -s -k -H "Content-Type: application/json" -H "Authorization: F9H4H43Wn4" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.152:8888/devices|jq '.Devices[0].Mode.modes[0]'
[2018-4-15 19:08:35] [Climatizzatore] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer F9H4H43Wn4" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.152:8888/devices|jq '.Devices[0].Temperatures[0].current'
[2018-4-15 19:08:35] [Climatizzatore2] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer 1VaH3i120U" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.149:8888/devices|jq '.Devices[0].Temperatures[0].current'
[2018-4-15 19:08:35] [Climatizzatore2] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer 1VaH3i120U" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.149:8888/devices|jq '.Devices[0].Mode.modes[0]'
[2018-4-15 19:08:35] [Climatizzatore2] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer 1VaH3i120U" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.149:8888/devices|jq '.Devices[0].Temperatures[0].desired'
[2018-4-15 19:08:35] [Climatizzatore2] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer 1VaH3i120U" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.149:8888/devices|jq '.Devices[0].Operation.power'
[2018-4-15 19:08:35] [Climatizzatore2] Mettere modalita
[2018-4-15 19:08:35] [Climatizzatore2] curl -s -k -H "Content-Type: application/json" -H "Authorization: 1VaH3i120U" --cert /homebridge/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.149:8888/devices|jq '.Devices[0].Mode.modes[0]'
[2018-4-15 19:08:36] [Climatizzatore2] Power function failed /bin/sh: jq: not found
(23) Failed writing body

[2018-4-15 19:08:36] [Climatizzatore2] undefinedazz
[2018-4-15 19:08:36] [Climatizzatore2] Power function failed /bin/sh: jq: not found

[2018-4-15 19:08:36] [Climatizzatore2] undefinedNON LO SO
[2018-4-15 19:08:36] [Climatizzatore2] Power function failed /bin/sh: jq: not found

/homebridge/node_modules/homebridge-samsung-airconditioner/index.js:180
                     callback(null, body); //Mettere qui ritorno di stdout? o solo callback()
                     ^
Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at SamsungAirco.<anonymous> (/homebridge/node_modules/homebridge-samsung-airconditioner/index.js:180:22)
    at /homebridge/node_modules/homebridge-samsung-airconditioner/index.js:31:9
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)

Thank you

**Comment by cicciovo** [comment]
For this error: “Power function failed /bin/sh: jq: not found” 
you should install jq 😉

**Comment by HajLender** [comment]
Great thank you again! Now it works.

If anybody else would like to install it to oznu/homebridge, I used this command:
`apk add --no-cache jq`
