### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by neobeppe** [cicciovo/homebridge-samsung-airconditioner#6]
Ho questo log e non homekit mi dice che l'accessorio non risponde:

`[6/22/2018, 6:28:08 PM] [Climatizzatore Salotto] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer 3450Y3SiOD" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.76:8888/devices|jq '.Devices[0].Mode.modes[0]'
[6/22/2018, 6:28:08 PM] [Climatizzatore Salotto] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer 3450Y3SiOD" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.76:8888/devices|jq '.Devices[0].Temperatures[0].desired'
[6/22/2018, 6:28:08 PM] [Climatizzatore Salotto] Mettere modalita
[6/22/2018, 6:28:08 PM] [Climatizzatore Salotto] curl -s -k -H "Content-Type: application/json" -H "Authorization: 3450Y3SiOD" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.76:8888/devices|jq '.Devices[0].Mode.modes[0]'
[6/22/2018, 6:28:08 PM] [Climatizzatore Salotto] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer 3450Y3SiOD" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.76:8888/devices|jq '.Devices[0].Temperatures[0].current'
[6/22/2018, 6:28:08 PM] [Climatizzatore Salotto] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer 3450Y3SiOD" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.76:8888/devices|jq '.Devices[0].Operation.power'
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] Power function OK
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] 
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] Temperatura corrente: NaN
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] azz
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] Power function OK
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] 
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] 
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] azz
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] TEMPERTURA DESIDERTA
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] 
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] NaN
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] Power function OK
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] 
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] 
[6/22/2018, 6:28:09 PM] [Climatizzatore Salotto] NON LO SO
`

**Comment by cicciovo** [comment]
Non ti trova il comando js .... dovresti installare pure quello. Sudo brew install js

Inviato da iPhone

Il giorno 22 giu 2018, alle ore 20:22, Giuseppe Travasoni <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Ciao, ho correttamente installato il plugin, fatto il setup dei condizionatori, ma fa crashare homebridge:

`[6/22/2018, 6:15:36 PM] [Climatizzatore Camera] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer mYCm24rn91" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.83:8888/devices|jq<https://192.168.1.83:8888/devices%7Cjq> '.Devices[0].Temperatures[0].current'
[6/22/2018, 6:15:36 PM] [Climatizzatore Camera] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer mYCm24rn91" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.83:8888/devices|jq<https://192.168.1.83:8888/devices%7Cjq> '.Devices[0].Temperatures[0].desired'
[6/22/2018, 6:15:36 PM] [Climatizzatore Camera] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer mYCm24rn91" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.83:8888/devices|jq<https://192.168.1.83:8888/devices%7Cjq> '.Devices[0].Mode.modes[0]'
[6/22/2018, 6:15:36 PM] [Climatizzatore Camera] Mettere modalita
[6/22/2018, 6:15:36 PM] [Climatizzatore Camera] curl -s -k -H "Content-Type: application/json" -H "Authorization: mYCm24rn91" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.83:8888/devices|jq<https://192.168.1.83:8888/devices%7Cjq> '.Devices[0].Mode.modes[0]'
[6/22/2018, 6:15:36 PM] [Climatizzatore Camera] curl -s -k -H "Content-Type: application/json" -H "Authorization: Bearer mYCm24rn91" --cert /usr/local/lib/node_modules/homebridge-samsung-airconditioner/ac14k_m.pem --insecure -X GET https://192.168.1.83:8888/devices|jq<https://192.168.1.83:8888/devices%7Cjq> '.Devices[0].Operation.power'
[6/22/2018, 6:15:37 PM] [Climatizzatore Camera] Power function failed /bin/sh: 1: jq: not found

[6/22/2018, 6:15:37 PM] [Climatizzatore Camera] undefinedNON LO SO
[6/22/2018, 6:15:37 PM] [Climatizzatore Camera] Power function failed /bin/sh: 1: jq: not found

[6/22/2018, 6:15:37 PM] [Climatizzatore Camera] undefinedazz
[6/22/2018, 6:15:37 PM] [Climatizzatore Camera] Power function failed /bin/sh: 1: jq: not found

/opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12
throw new Error("This callback function has already been called by someone else; it can only be called one time.");
^

Error: This callback function has already been called by someone else; it can only be called one time.
at /opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
at Object. (/opt/nodejs/lib/node_modules/homebridge-samsung-airconditioner/index.js:180:22)
at /opt/nodejs/lib/node_modules/homebridge-samsung-airconditioner/index.js:31:9
at ChildProcess.exithandler (child_process.js:213:5)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:852:16)
at Socket. (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
`

**Comment by cicciovo** [comment]
Scusa, volevo dire jq, infatti se vedi l errore che di da: Power function failed /bin/sh: 1: jq: not found, dice appunto che non trova jq, installalo e vedi che funzionerà 😉

**Comment by neobeppe** [comment]
Ho installato jq e ora non crasha ma ho altri errori, ho modificato la issue con il log aggiornato

**Comment by cicciovo** [comment]
È un errore che anche altri utenti hanno riscontrato, vedi gli altri post.... dovresti giocare la prima volta un po’ con l app di Samsung, e o accendere o spegnere il clima... vedi l ultimo post scritto dagli altri utenti e troverai la soluzione. Fammi sapere

**Comment by simoneras** [comment]
Ciao a me funziona tutto tranne il set di temperatura. Ho avuto probkemi di installazione ma ho usato sudo npm install -g --unsafe-perm homebridge-samsung-airconditioner ed è partito tutto. Dopo ho installato jq.

**Comment by simoneras** [comment]
Ciao a tutti evda un po di tempo che ho questo problema; con i condizionatori inseriti in accessori si blocca homebridge e non aggiorna la app casa di ios, se libelimino va benissimo. Potete aiutarmi?

Grazie
